# Config for air live reloading
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  exclude_dir = ["tmp", "vendor"]
  exclude_file = ["README.md"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  delay = 1000